import 'package:flutter/material.dart';
final baseurl = "https://www.cowdiar.com/"; // https://www.example.com
final version = "api/v1";
final url ="/home";
final register ="/register-user";
final loginurl ="/login-user";
final categorylink = "/categories";
final subcatlink = "/sub-categories/";
final forgetpasslink = "/forgot-password";
final searchurl = "/s";
final sitedetails = "/app-info";
final profile='/my-profile';
final manage="/manage-orders";
final sellingorder="/selling-orders";
final orderdetails="/order-details";
final sendmsg="/send-message";
final notificationlink ="/notifications";
final manrequestlink = "/manage-requests";
final statuscheck = "/get-online-status";
final inboxbox="/inbox";
final inboxdetails='/single-message';
final inboxsend='/send-new-message';
final viewofferlink ='/view-offers';
final requestlink ='/request-action';
final actionlink ='/single-message-action';
final notificationactionlink ='/notification-action';
final sendfeedback ='/send-feedback';
final contactuspage ='/contact-me';
final cartpagelink ='/cart';
final addcartpage ='/add-to-cart';
final removecart ='/remove-from-cart';
final changecart ='/change-quantity';
final coupon= '/apply-coupon';
final updateonlinestatus= '/update-online-status';
final postrequest= '/post-request';
final privacypolicy='/page/privacy-policy';
final termslink='/terms_and_conditions';
final getenquirytypes='/get-enquiry-types';
final getnotifaction='/seller-push-notification-setting';
final postnotifaction='/push-notification-setting';
final deliverapidate='/delivery-times';
final primarycolor = Colors.blue;
final secondercolor = Colors.black54;
// login and reginer screen wave color
final wavefirst = Colors.red[100];
final wavesecond = Colors.red[200];

// all over application icon color overlay
final iconcolor = Colors.red;