// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkvIUVKxBC2Vy4OBFAs45kEe38_DnSV_A',
    appId: '1:413744857306:android:7676b3cf32befbed2625e3',
    messagingSenderId: '413744857306',
    projectId: 'cowdiar-mobile',
    storageBucket: 'cowdiar-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjIHb0letCKDi2uk74l8GkfjSEAbYUiZU',
    appId: '1:413744857306:ios:069c1ec7e2e836162625e3',
    messagingSenderId: '413744857306',
    projectId: 'cowdiar-mobile',
    storageBucket: 'cowdiar-mobile.appspot.com',
    iosClientId: '413744857306-kecok0nfi32tv00l27t0ksp8d8n5945c.apps.googleusercontent.com',
    iosBundleId: 'com.cowdiar.mobileapp',
  );
}
